---
http:
  routers:
    to-jellyfin-Coitus:
      rule: "Host(`jellyfin.coitus.io`)"
      service: jellyfin
      
    to-jellyfin-Coitus-secure:
      rule: "Host(`jellyfin.coitus.io`)"
      service: jellyfin
#      tls:
#        certResolver: letsencrypt

#    to-jellyfin-8bitshit:
#      rule: "Host(`jellyfin.8bitshit.com`)"
#      service: jellyfin

#    to-jellyfin-8bitshit-secure:
#      rule: "Host(`jellyfin.8bitshit.com`)"
#      service: jellyfin
#      tls:
#        certResolver: letsencrypt
        
  middlewares:
    my-torblock:
      plugin:
        torblock:
          AddressListURL: https://check.torproject.org/exit-addresses
          Enabled: "true"
          UpdateInterval: "3600"
          
    my-plugin-log4shell:
      plugin:
        plugin-log4shell:
          errorCode: "200"
        
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096