---
http:
  routers:
    to-plexia-Coitus:
      rule: "Host(`plexia.coitus.io`)"
      service: plexia
      
    to-plexia-Coitus-secure:
      rule: "Host(`plexia.coitus.io`)"
      service: plexia
#      tls:
#        certResolver: letsencrypt

#    to-plexia-8bitshit:
#      rule: "Host(`plexia.8bitshit.com`)"
#      service: plexia

#    to-plexia-8bitshit-secure:
#      rule: "Host(`plexia.8bitshit.com`)"
#      service: plexia
#      tls:
#        certResolver: letsencrypt

  middlewares:
    my-torblock:
      plugin:
        torblock:
          AddressListURL: https://check.torproject.org/exit-addresses
          Enabled: "true"
          UpdateInterval: "3600"
          
    my-plugin-log4shell:
      plugin:
        plugin-log4shell:
          errorCode: "200"
        
  services:
    plexia:
      loadBalancer:
        servers:
          - url: http://10.0.1.5:32400